# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Visualization\dist\main\visualization\GUI\pdw\channelui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_channelUi(object):
    def setupUi(self, channelUi):
        channelUi.setObjectName("channelUi")
        channelUi.resize(1080, 200)
        channelUi.setMinimumSize(QtCore.QSize(0, 200))
        channelUi.setMaximumSize(QtCore.QSize(16777215, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(channelUi)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(channelUi)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainPlotWidget = QtWidgets.QWidget(self.frame)
        self.mainPlotWidget.setObjectName("mainPlotWidget")
        self.mainPlotLayout = QtWidgets.QHBoxLayout(self.mainPlotWidget)
        self.mainPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.mainPlotLayout.setSpacing(0)
        self.mainPlotLayout.setObjectName("mainPlotLayout")
        self.horizontalLayout.addWidget(self.mainPlotWidget)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(channelUi)
        QtCore.QMetaObject.connectSlotsByName(channelUi)

    def retranslateUi(self, channelUi):
        _translate = QtCore.QCoreApplication.translate
        channelUi.setWindowTitle(_translate("channelUi", "Form"))
