# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Visualization\visualization\GUI\pdw\exportWindowui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 114)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.exportTypeComboBox = QtWidgets.QComboBox(self.widget)
        self.exportTypeComboBox.setObjectName("exportTypeComboBox")
        self.exportTypeComboBox.addItem("")
        self.exportTypeComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.exportTypeComboBox)
        self.browsBtn = QtWidgets.QPushButton(self.widget)
        self.browsBtn.setObjectName("browsBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.browsBtn)
        self.pathLineEdit = QtWidgets.QLineEdit(self.widget)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pathLineEdit)
        self.exportBtn = QtWidgets.QPushButton(self.widget)
        self.exportBtn.setObjectName("exportBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.exportBtn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Export to :"))
        self.exportTypeComboBox.setItemText(0, _translate("Form", "text"))
        self.exportTypeComboBox.setItemText(1, _translate("Form", "csv"))
        self.browsBtn.setText(_translate("Form", "Brows"))
        self.exportBtn.setText(_translate("Form", "Export"))
