# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Visualization\visualization\GUI\settings\mainsettingsui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1147, 589)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pdwSettingsGroupBox = QtWidgets.QGroupBox(self.widget)
        self.pdwSettingsGroupBox.setObjectName("pdwSettingsGroupBox")
        self.groupBox = QtWidgets.QGroupBox(self.pdwSettingsGroupBox)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 119, 87))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 22, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.scrollRadioButton.setChecked(True)
        self.scrollRadioButton.setObjectName("scrollRadioButton")
        self.verticalLayout.addWidget(self.scrollRadioButton)
        self.nonScrollRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.nonScrollRadioButton.setObjectName("nonScrollRadioButton")
        self.verticalLayout.addWidget(self.nonScrollRadioButton)
        self.horizontalLayout_2.addWidget(self.pdwSettingsGroupBox)
        self.signalSettingsGroupBox = QtWidgets.QGroupBox(self.widget)
        self.signalSettingsGroupBox.setObjectName("signalSettingsGroupBox")
        self.horizontalLayout_2.addWidget(self.signalSettingsGroupBox)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pdwSettingsGroupBox.setTitle(_translate("Form", "Pdw Settings"))
        self.groupBox.setTitle(_translate("Form", "Show Policy"))
        self.scrollRadioButton.setText(_translate("Form", "scroll"))
        self.nonScrollRadioButton.setText(_translate("Form", "non-scroll"))
        self.signalSettingsGroupBox.setTitle(_translate("Form", "Signal Settings"))
