# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sepeh\Desktop\Visualization\visualization\GUI\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.PDWTab = QtWidgets.QWidget()
        self.PDWTab.setObjectName("PDWTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PDWTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pdwWidget = QtWidgets.QWidget(self.PDWTab)
        self.pdwWidget.setObjectName("pdwWidget")
        self.pdwLayout = QtWidgets.QVBoxLayout(self.pdwWidget)
        self.pdwLayout.setContentsMargins(0, 0, 0, 0)
        self.pdwLayout.setSpacing(0)
        self.pdwLayout.setObjectName("pdwLayout")
        self.verticalLayout_2.addWidget(self.pdwWidget)
        self.tabWidget.addTab(self.PDWTab, "")
        self.SignalForm = QtWidgets.QWidget()
        self.SignalForm.setObjectName("SignalForm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SignalForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.signalWidget = QtWidgets.QWidget(self.SignalForm)
        self.signalWidget.setObjectName("signalWidget")
        self.signalLayout = QtWidgets.QVBoxLayout(self.signalWidget)
        self.signalLayout.setContentsMargins(0, 0, 0, 0)
        self.signalLayout.setSpacing(0)
        self.signalLayout.setObjectName("signalLayout")
        self.verticalLayout_3.addWidget(self.signalWidget)
        self.tabWidget.addTab(self.SignalForm, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PDWTab), _translate("MainWindow", "PDW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SignalForm), _translate("MainWindow", "SIGNAL"))
