# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Visualization\visualization\GUI\pdw\markerinfoui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(180, 374)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 156, 233))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.markerInfoGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.markerInfoGroupBox.setObjectName("markerInfoGroupBox")
        self.markerInfoLayout = QtWidgets.QFormLayout(self.markerInfoGroupBox)
        self.markerInfoLayout.setContentsMargins(-1, 22, -1, -1)
        self.markerInfoLayout.setObjectName("markerInfoLayout")
        self.horizontalLayout.addWidget(self.markerInfoGroupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setContentsMargins(-1, 22, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.timeLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.timeLineEdit.setReadOnly(True)
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeLineEdit)
        self.valLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.valLineEdit.setReadOnly(True)
        self.valLineEdit.setObjectName("valLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.valLineEdit)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.markerInfoGroupBox.setTitle(_translate("Form", "Line Marker data"))
        self.groupBox.setTitle(_translate("Form", "Point Marker"))
        self.label.setText(_translate("Form", "Time:"))
        self.label_2.setText(_translate("Form", "Value:"))
