# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sepeh\Desktop\Visualization\visualization\GUI\pdw\pdwtools.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PdwTools(object):
    def setupUi(self, PdwTools):
        PdwTools.setObjectName("PdwTools")
        PdwTools.resize(289, 275)
        self.verticalLayout = QtWidgets.QVBoxLayout(PdwTools)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolsGroupBox = QtWidgets.QGroupBox(PdwTools)
        self.toolsGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.toolsGroupBox.setObjectName("toolsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.toolsGroupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.clearBtn = QtWidgets.QPushButton(self.toolsGroupBox)
        self.clearBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.clearBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.clearBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../../Resources/icons/delete.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.clearBtn.setIcon(icon)
        self.clearBtn.setIconSize(QtCore.QSize(40, 40))
        self.clearBtn.setObjectName("clearBtn")
        self.gridLayout.addWidget(self.clearBtn, 0, 3, 1, 1)
        self.newRadarBtn = QtWidgets.QPushButton(self.toolsGroupBox)
        self.newRadarBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.newRadarBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.newRadarBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../../Resources/icons/radar.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.newRadarBtn.setIcon(icon1)
        self.newRadarBtn.setIconSize(QtCore.QSize(40, 40))
        self.newRadarBtn.setObjectName("newRadarBtn")
        self.gridLayout.addWidget(self.newRadarBtn, 1, 3, 1, 1)
        self.showDataBtn = QtWidgets.QPushButton(self.toolsGroupBox)
        self.showDataBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.showDataBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.showDataBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../../Resources/icons/play-button.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.showDataBtn.setIcon(icon2)
        self.showDataBtn.setIconSize(QtCore.QSize(40, 40))
        self.showDataBtn.setObjectName("showDataBtn")
        self.gridLayout.addWidget(self.showDataBtn, 0, 2, 1, 1)
        self.selectAllBtn = QtWidgets.QPushButton(self.toolsGroupBox)
        self.selectAllBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.selectAllBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.selectAllBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../../Resources/icons/select_all.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.selectAllBtn.setIcon(icon3)
        self.selectAllBtn.setIconSize(QtCore.QSize(40, 40))
        self.selectAllBtn.setObjectName("selectAllBtn")
        self.gridLayout.addWidget(self.selectAllBtn, 1, 1, 1, 1)
        self.selectFileBtn = QtWidgets.QPushButton(self.toolsGroupBox)
        self.selectFileBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.selectFileBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.selectFileBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../../Resources/icons/download-file.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../Resources/icons/download-file.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.selectFileBtn.setIcon(icon4)
        self.selectFileBtn.setIconSize(QtCore.QSize(40, 40))
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.gridLayout.addWidget(self.selectFileBtn, 0, 1, 1, 1)
        self.selectBtn = QtWidgets.QPushButton(self.toolsGroupBox)
        self.selectBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.selectBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.selectBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\sepeh\\Desktop\\Visualization\\visualization\\GUI\\pdw\\../../Resources/icons/select.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.selectBtn.setIcon(icon5)
        self.selectBtn.setIconSize(QtCore.QSize(60, 60))
        self.selectBtn.setCheckable(True)
        self.selectBtn.setObjectName("selectBtn")
        self.gridLayout.addWidget(self.selectBtn, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.toolsGroupBox)

        self.retranslateUi(PdwTools)
        QtCore.QMetaObject.connectSlotsByName(PdwTools)

    def retranslateUi(self, PdwTools):
        _translate = QtCore.QCoreApplication.translate
        PdwTools.setWindowTitle(_translate("PdwTools", "Form"))
        self.toolsGroupBox.setTitle(_translate("PdwTools", "Tools"))
