# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sepeh\Desktop\Visualization\dist\main\visualization\GUI\pdw\pdwui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1418, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(self.centralwidget)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataInformationWidget = QtWidgets.QWidget(self.leftFrame)
        self.dataInformationWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.dataInformationWidget.setObjectName("dataInformationWidget")
        self.dataInformationLayout = QtWidgets.QHBoxLayout(self.dataInformationWidget)
        self.dataInformationLayout.setContentsMargins(11, 11, 11, 11)
        self.dataInformationLayout.setSpacing(0)
        self.dataInformationLayout.setObjectName("dataInformationLayout")
        self.verticalLayout.addWidget(self.dataInformationWidget)
        self.plotWidget = QtWidgets.QWidget(self.leftFrame)
        self.plotWidget.setObjectName("plotWidget")
        self.plotLayout = QtWidgets.QHBoxLayout(self.plotWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout.addWidget(self.plotWidget)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.rightFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.rightFrameLayout = QtWidgets.QVBoxLayout(self.rightFrame)
        self.rightFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.rightFrameLayout.setSpacing(0)
        self.rightFrameLayout.setObjectName("rightFrameLayout")
        self.horizontalLayout.addWidget(self.rightFrame)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1418, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
