# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Visualization\visualization\GUI\pdw\pdwui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1436, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftWidget = QtWidgets.QWidget(self.widget_2)
        self.leftWidget.setObjectName("leftWidget")
        self.leftFrameLayout = QtWidgets.QVBoxLayout(self.leftWidget)
        self.leftFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.leftFrameLayout.setSpacing(7)
        self.leftFrameLayout.setObjectName("leftFrameLayout")
        self.horizontalLayout.addWidget(self.leftWidget)
        self.rightWidget = QtWidgets.QWidget(self.widget_2)
        self.rightWidget.setObjectName("rightWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoWidget = QtWidgets.QWidget(self.rightWidget)
        self.infoWidget.setObjectName("infoWidget")
        self.infoWidgetLayout = QtWidgets.QHBoxLayout(self.infoWidget)
        self.infoWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.infoWidgetLayout.setSpacing(0)
        self.infoWidgetLayout.setObjectName("infoWidgetLayout")
        self.verticalLayout.addWidget(self.infoWidget)
        self.reviewWidget = QtWidgets.QWidget(self.rightWidget)
        self.reviewWidget.setObjectName("reviewWidget")
        self.reviewLayout = QtWidgets.QHBoxLayout(self.reviewWidget)
        self.reviewLayout.setContentsMargins(0, 0, 0, 0)
        self.reviewLayout.setSpacing(0)
        self.reviewLayout.setObjectName("reviewLayout")
        self.verticalLayout.addWidget(self.reviewWidget)
        self.plotWidget = QtWidgets.QWidget(self.rightWidget)
        self.plotWidget.setObjectName("plotWidget")
        self.plotLayout = QtWidgets.QHBoxLayout(self.plotWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout.addWidget(self.plotWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 20)
        self.horizontalLayout.addWidget(self.rightWidget)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
