# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sepeh\Desktop\Visualization\dist\main\visualization\GUI\signal\signalinformationui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 154)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.channelNumberComboBox = QtWidgets.QComboBox(self.widget)
        self.channelNumberComboBox.setObjectName("channelNumberComboBox")
        self.channelNumberComboBox.addItem("")
        self.channelNumberComboBox.addItem("")
        self.channelNumberComboBox.addItem("")
        self.channelNumberComboBox.addItem("")
        self.channelNumberComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.channelNumberComboBox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.signCheckBox = QtWidgets.QCheckBox(self.widget)
        self.signCheckBox.setChecked(True)
        self.signCheckBox.setObjectName("signCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.signCheckBox)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.bigEndinCheckBox = QtWidgets.QCheckBox(self.widget)
        self.bigEndinCheckBox.setChecked(True)
        self.bigEndinCheckBox.setObjectName("bigEndinCheckBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bigEndinCheckBox)
        self.verticalLayout.addWidget(self.widget)
        self.applyBtn = QtWidgets.QPushButton(Form)
        self.applyBtn.setObjectName("applyBtn")
        self.verticalLayout.addWidget(self.applyBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Number of Channels :"))
        self.channelNumberComboBox.setItemText(0, _translate("Form", "1"))
        self.channelNumberComboBox.setItemText(1, _translate("Form", "2"))
        self.channelNumberComboBox.setItemText(2, _translate("Form", "3"))
        self.channelNumberComboBox.setItemText(3, _translate("Form", "4"))
        self.channelNumberComboBox.setItemText(4, _translate("Form", "5"))
        self.label_2.setText(_translate("Form", "Data Sign:"))
        self.signCheckBox.setText(_translate("Form", "signed"))
        self.label_3.setText(_translate("Form", "Endin:"))
        self.bigEndinCheckBox.setText(_translate("Form", "big endin"))
        self.applyBtn.setText(_translate("Form", "apply"))
